[tool.poetry]
name = "coursework3"
version = "0.1.0"
description = ""
authors = ["Алексей Денисенко <elvis.presly.039127@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
